config/routes.rb
Tacosmode::Application.routes.draw do

  resources :stock_items

  match "users" => 'branches#index_users', :as=>'users'

  resources :products

  get "branches/:branch_id/transfers/new1" => 'transfers#new1', :as=>'new1_branch_transfer'  do
      resources :transfered_products
    end

  resources :branches do

    resources :transfers do
      resources :transfered_products
    end

    match "/transfers/:id/entry" => "transfers#entry", :as => 'entry' do
      resources :transfered_products
    end

  end

   root :to => 'branches#index'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :stock_items
  has_many :transfers
  attr_accessible :location, :name
accepts_nested_attributes_for :transfers
accepts_nested_attributes_for :stock_items
validates :name, :location, :presence => true

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @branches }
    end
  end

  def index_users

  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    @branch = Branch.find(params[:id])

    @transfers = @branch.transfers.order('created_at DESC')

    @transfers_list_e = Transfer.where(:destination=>(params[:id]))

    @transfers_entry = Transfer.where(:status => 'pending', :destination =>(params[:id]))

    respond_to do |format|

      format.html # show.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.json
  def new
    @branch = Branch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(params[:branch])

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render json: @branch, status: :created, location: @branch }
      else
        format.html { render action: "new" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.json
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to branches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<fieldset>
  <%= form_for(@branch, :html=>{:class=>"form-horizontal"}) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class=> "control-label"%>
    <div class="controls">
      <%= f.text_field :name, :class =>"input-xlarge"%>
      </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class=> "control-label"%>
    <div class="controls">
      <%= f.text_area :location, :class =>"input-xlarge", :rows=>3%>
      </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Crear', :class =>"btn btn-primary" %>
    <%= link_to 'Back', branches_path, :class =>"btn" %>

  </div>
<% end %>
</fieldset>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<div style="padding:20px 0 30px">
  <h1>Lista de sucursales</h1>
</div>
<% if @branches.empty?  %>
  <h3>Agrega una sucursal </h3>
<% elsif %>


<table class="table table-striped">
<thead>
  <tr>

    <th>Nombre</th>
    <th>Ubicación</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @branches.each do |branch| %>
  <tr>
    <td><%= branch.name %></td>
    <td><%= branch.location %></td>
    <td><%= link_to 'Show', branch %></td>
    <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
    <td><%= link_to 'Destroy', branch, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
</tbody>
<% end %>
</table>
<% end  %>
<br />

<%= link_to 'Nueva Sucursal', new_branch_path, :class => "btn btn-primary" %>

app/views/branches/new.html.erb
<div style="padding:10px 0 10px">
  <h1>Nueva Sucursal</h1>
</div>

<%= render 'form' %>

app/views/branches/show.html.erb
<p ID="NOTICE"><%= notice %></p>

<p style="font-size:15px">
  <b>Name:</b>
  <%= @branch.name %>
</p>

<p style="font-size:15px">
  <b>Location:</b>
  <%= @branch.location %>
</p>

    <div class="row">
      <div class="span4" style="float:right">
        <h2>Dar de alta un movimiento</h2>
        <%=link_to "Salida", new_branch_transfer_path(@branch), :class=>"btn btn-primary" %>
        <!--link para dar de altaa un abastecimiento de proveedor-->
        <%=link_to "Proveedor", new1_branch_transfer_path(@branch), :class=>"btn btn-primary" %>
        <%= render :partial => "transfers/trans_entry_partial", :locals => {:trans_list => @transfers_entry}%>

      </div>
      <div class="span8">
        <h2>Últimos Movimientos</h2>
        <h3>Salidas</h3>
          <%= render :partial => "transfers/trans_partial", :locals => {:transfer_list => @transfers}%>
        <h3>Entradas</h3>
          <%= render :partial => "transfers/trans_entry_list", :locals => {:transfer_list => @transfers_list_e}%>



        <%= link_to 'Edit', edit_branch_path(@branch), :class=>"btn btn-primary" %> |
        <%= link_to 'Back', branches_path, :class=>"btn" %>

</div>