config/routes.rb
Tacosmode::Application.routes.draw do

  resources :stock_items

  match "users" => 'branches#index_users', :as=>'users'

  resources :products

  get "branches/:branch_id/transfers/new1" => 'transfers#new1', :as=>'new1_branch_transfer'  do
      resources :transfered_products
    end

  resources :branches do

    resources :transfers do
      resources :transfered_products
    end

    match "/transfers/:id/entry" => "transfers#entry", :as => 'entry' do
      resources :transfered_products
    end

  end

   root :to => 'branches#index'

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :branch
  has_many :transfered_products
  attr_accessible :date_output, :date_supply, :mode, :name_dealer, :destination, :transfered_products_attributes, :status
  validates :destination, :name_dealer, :presence => true

  before_create :create_status
  accepts_nested_attributes_for :transfered_products

  def create_status
    self.status = "pending"
  end

DEALER = ['Roberto', 'Sergio', 'Carlos']
MODE = ['Salida', 'Cierre', 'Proveedor']

  class << self
    DEALER.each do |name_dealer|
      define_method "cat_#{name_dealer}" do
        name_dealer
      end
    end
    MODE.each do |name_mode|
      define_method "cat_#{name_mode}" do
        name_mode
      end
    end

  end


end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_filter :get_branch

  def get_branch
    @branch = Branch.find(params[:branch_id])
  end


  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transfers }
    end
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
    @transfer = @branch.transfers.find(params[:id])
    @transfered_product = @transfer.transfered_products.build
    @product = Product.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transfer }
    end
  end

  # GET /transfers/new
  # GET /transfers/new.json
  def new
    @transfer = @branch.transfers.new
    1.times {@transfer.transfered_products.build}
    @condicion = 2
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transfer }
    end
  end


  def new1
    @transfer = @branch.transfers.new
    1.times {@transfer.transfered_products.build}
    @condicion = 2
    respond_to do |format|
      format.html # new_provision.html.erb
      format.json { render json: @transfer }
    end
  end


  # GET /transfers/1/edit
  def edit
    @transfer = Transfer.find(params[:id])
    @condicion = 2

  end

  def entry
    @transfer = Transfer.find(params[:id])
    @condicion = 1
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = @branch.transfers.create(params[:transfer])
    respond_to do |format|
      if @transfer.save
        format.html { redirect_to branch_transfer_path(@branch,@transfer), notice: 'Transfer was successfully created.' }
        format.json { render json: @transfer, status: :created, location: @transfer }
      else
        format.html { render action: "new" }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transfers/1
  # PUT /transfers/1.json
  def update
    @transfer = Transfer.find(params[:id])

    respond_to do |format|
      if @transfer.update_attributes(params[:transfer])
        format.html { redirect_to branch_path(@branch)}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer = Transfer.find(params[:id])
    @transfer.destroy

    respond_to do |format|
      format.html { redirect_to transfers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for([@branch, @transfer],:html=>{:class=>"form-horizontal"}) do |f| %>
  <% if @transfer.errors.any? %>
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  <% end %>

  <fieldset>

  <div class="control-group">
    <%= f.label 'Tipo de transferencia', :class=>"control-label" %>
    <div class="controls">
    <%= select(:transfer, :mode, Transfer::MODE.collect {|cat| [cat,cat] }) %>
    </div>
  </div>

  <div class="control-group">
  <%= f.label 'Destino Entrada', :class=>"control-label" %>
    <div class="controls">
    <%= f.collection_select(:destination, Branch.all, :id, :name) %>
    </div>
  </div>

  <div class="control-group">
  <%= f.label 'Repartidor', :class=>"control-label" %>
    <div class="controls">
    <%= f.select(:name_dealer, Transfer::DEALER.collect {|cat| [cat,cat] }) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Fecha salida', :class=>"control-label" %>
    <div class="controls">
    <%= f.text_field :date_output %>
    </div>
  </div>
    <div class="control-group">
    <% f.label 'Fecha salida' %>
    <div class="controls">
    <% f.text_field :date_supply %>
    </div>
  </div>
  <h3>Agregar Productos<h3>
      <form class="well form-inline">
      <%= f.fields_for :transfered_products do |builder|  %>
        <%= render 'transfered_product_fields', {:f => builder, :condicion=>@condicion} %>
      <% end %>
    </form>
      <div id="onenter" style="padding:0px 50px">
      <%= link_to_add_fields "+", f, :transfered_products %>
      </div>
  <div class="form-actions">
    <%= f.submit 'Guardar', :class=>"btn btn-primary"%>
    <%= link_to 'Back', branch_path(@branch), :class=>"btn" %>
  </div>
  </fieldset>
<% end %>

app/views/transfers/_form_entry.html.erb
<%= form_for([@branch, @transfer],:html=>{:class=>"form-horizontal"}) do |f| %>
 <fieldset>
  <%= f.hidden_field :status, :value => 'succes' %>
  <div class="control-group">
  <%= f.label :name_dealer, :class=>"control-label" %>
    <div class="controls">
      <%= f.select(:name_dealer, Transfer::DEALER.collect {|cat| [cat,cat] },{}, {:disabled => true}) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :date_supply, "Fecha de entrada", :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :date_supply %>
    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function () {
        $('#transfer_date_supply').datepicker();
        $('#transfer_date_supply').datepicker('option', {dateFormat: 'yy-mm-dd'});
        $("#startDate").datepicker({dateFormat: 'yy-mm-dd'});
    });
  </script>

  <h3>Productos<h3>
      <form class="well form-inline">
      <%= f.fields_for :transfered_products do |builder|  %>
        <%= render 'transfered_product_fields', {:f => builder, :condicion=>@condicion} %>
      <% end %>
      </form>
<div class="form-actions">
    <%= f.submit 'Guardar', :class=>"btn btn-primary"%>
    <%= link_to 'Back', branch_path(@branch), :class=>"btn" %>
  </div>
  </fieldset>
<% end %>

app/views/transfers/_form_provider.html.erb
<%= form_for([@branch, @transfer],:html=>{:class=>"form-horizontal"}) do |f| %>
 <fieldset>
  <%= f.hidden_field :status, :value => 'succes' %>

  <div class="control-group">
    <%= f.label :date_supply, "Fecha de entrada", :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :date_supply %>
    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function () {
        $('#transfer_date_supply').datepicker();
        $('#transfer_date_supply').datepicker('option', {dateFormat: 'yy-mm-dd'});
        $("#startDate").datepicker({dateFormat: 'yy-mm-dd'});
    });
  </script>

  <h3>Productos<h3>
      <form class="well form-inline">
      <%= f.fields_for :transfered_products do |builder|  %>
        <%= render 'transfered_product_fields', {:f => builder, :condicion=>@condicion} %>
      <% end %>
      </form>
<div class="form-actions">
    <%= f.submit 'Guardar', :class=>"btn btn-primary"%>
    <%= link_to 'Regresar', branch_path(@branch), :class=>"btn" %>
  </div>
  </fieldset>
<% end %>

app/views/transfers/_trans_entry_list.html.erb
<% transfer_list.each do |transfer| %>
<table class="table table-condensed">
  <thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
  <tr>
    <td><%= transfer.name_dealer %></td>
    <td><%= transfer.date_supply %></td>
    <td><%= link_to 'Show', branch_transfer_path(transfer.branch,transfer), :class=>"btn btn-primary" %></td>
  </tr>
</tbody>
</table>


<% end  %>

app/views/transfers/_trans_entry_partial.html.erb
<% trans_list.each do |transfer| %>

<table class="table">
  <thead>
  <tr>
    <th>Name dealer</th>
    <th>Date output</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><%= transfer.name_dealer %></td>
    <td><%= transfer.date_output %></td>
    <td><%= link_to 'Entrada', branch_entry_path(@branch,transfer),:class=>"btn btn-primary"  %></td>
  </tr>
</tbody>
</table>


<% end  %>

app/views/transfers/_trans_partial.html.erb
<% transfer_list.each do |transfer| %>
<table class="table table-condensed">
  <thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
  <tr>
    <td><%= transfer.mode %></td>
    <td><%= transfer.name_dealer %></td>
    <td><%= transfer.date_output %></td>
    <td><%= transfer.date_supply %></td>
    <td><%= link_to 'Show', branch_transfer_path(@branch,transfer), :class=>"btn btn-primary" %></td>
    <td><%= link_to 'Edit', edit_branch_transfer_path(@branch,transfer),:class=>"btn btn-primary"  %></td>
    <td><%#= link_to 'Destroy', transfer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
</tbody>
</table>


<% end  %>

app/views/transfers/_transfered_product_fields.html.erb
<div class="fields">

  <%= f.label "Cantidad", :class=>"control-label" %>
  <% if @condicion == 1 %>
    <%= f.text_field :quantity, :class=>"input-small", :placeholder=>'Cantidad', :disabled => true %>

    <%= f.select(:product_id, Product.all.collect {|p|[p.sku, p.id]}, {:prompt => 'Selecciona un Producto'}, {:disabled => true})%>

    <%= f.text_field :quantity_entry, :placeholder=>'Cantidad Recibida' %>

  <% else %>
    <%= f.text_field :quantity, :class=>"input-small", :placeholder=>'Cantidad', :value=>1 %>
    <%= f.select(:product_id, Product.all.collect {|p|[p.sku + "  " + p.name, p.id]}, {:prompt => 'Selecciona un Producto'}, :class => "enp" )%>
  <% end  %>

  <%= f.text_area :note, :rows=>"2", :placeholder=>'Agrega una Nota' %>


    <%= link_to_remove_fields "_", f %>

  </div>

app/views/transfers/edit.html.erb
<h1>Editing transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', branch_path(@branch) %>

app/views/transfers/entry.html.erb
<%= render 'form_entry'  %>

app/views/transfers/index.html.erb
<h1>Listing transfers</h1>

<table>
  <tr>
    <th>Branches</th>
    <th>Mode</th>
    <th>Name dealer</th>
    <th>Date output</th>
    <th>Date supply</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transfers.each do |transfer| %>
  <tr>
    <td><%= transfer.branches %></td>
    <td><%= transfer.mode %></td>
    <td><%= transfer.name_dealer %></td>
    <td><%= transfer.date_output %></td>
    <td><%= transfer.date_supply %></td>
    <td><%= link_to 'Show', transfer %></td>
    <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
    <td><%= link_to 'Destroy', transfer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New transfer</h1>

<%= render 'form' %>

<script type="text/javascript">
    $('select.enp:last').keyup(function(e){
      if(e.keyCode == 13) {
        $('#enterp').trigger('click');
        var f = $("select.enp:last").attr("id")
        alert(f);

      };
    });

$(document).ready(function(){$('#enterp').click (function(){$("select.enp").attr("id", function (arr) {return arr;}).each(function(){  });});
});
</script>

app/views/transfers/new1.html.erb
<%= render 'form_provider' %>

<script type="text/javascript" charset="utf-8">
  $(document).keyup(function(e){
      if(e.keyCode == 13) {
          $('#enterp').trigger('click');
      }
  });
</script>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mode:</b>
  <%= @transfer.mode %>
</p>

<p>
  <b>Name dealer:</b>
  <%= @transfer.name_dealer %>
</p>

<p>
  <b>Date output:</b>
  <%= @transfer.date_output %>
</p>

<p>
  <b>Date supply:</b>
  <%= @transfer.date_supply %>
</p>

<h3>Productos</h3>
<% for transfered_product in @transfer.transfered_products %>
  <%= transfered_product.quantity  %>
  <%= transfered_product.product_id  %>
<% end %>
<%= link_to 'Edit', edit_branch_transfer_path(@branch,@transfer), :class=>"btn btn-primary" %>
<%= link_to 'Back', branch_path(@branch), :class=>"btn btn-primary" %>