config/routes.rb
Tacosmode::Application.routes.draw do

  resources :stock_items

  match "users" => 'branches#index_users', :as=>'users'

  resources :products

  get "branches/:branch_id/transfers/new1" => 'transfers#new1', :as=>'new1_branch_transfer'  do
      resources :transfered_products
    end

  resources :branches do

    resources :transfers do
      resources :transfered_products
    end

    match "/transfers/:id/entry" => "transfers#entry", :as => 'entry' do
      resources :transfered_products
    end

  end

   root :to => 'branches#index'

end

app/models/stock_item.rb
class StockItem < ActiveRecord::Base
  belongs_to :branch
  belongs_to :product
  attr_accessible :quantity
end

app/controllers/stock_items_controller.rb
class StockItemsController < ApplicationController
  # GET /stock_items
  # GET /stock_items.json
  def index
    @stock_items = StockItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stock_items }
    end
  end

  # GET /stock_items/1
  # GET /stock_items/1.json
  def show
    @stock_item = StockItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stock_item }
    end
  end

  # GET /stock_items/new
  # GET /stock_items/new.json
  def new
    @stock_item = StockItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stock_item }
    end
  end

  # GET /stock_items/1/edit
  def edit
    @stock_item = StockItem.find(params[:id])
  end

  # POST /stock_items
  # POST /stock_items.json
  def create
    @stock_item = StockItem.new(params[:stock_item])

    respond_to do |format|
      if @stock_item.save
        format.html { redirect_to @stock_item, notice: 'Stock item was successfully created.' }
        format.json { render json: @stock_item, status: :created, location: @stock_item }
      else
        format.html { render action: "new" }
        format.json { render json: @stock_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stock_items/1
  # PUT /stock_items/1.json
  def update
    @stock_item = StockItem.find(params[:id])

    respond_to do |format|
      if @stock_item.update_attributes(params[:stock_item])
        format.html { redirect_to @stock_item, notice: 'Stock item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stock_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_items/1
  # DELETE /stock_items/1.json
  def destroy
    @stock_item = StockItem.find(params[:id])
    @stock_item.destroy

    respond_to do |format|
      format.html { redirect_to stock_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/views/stock_items/_form.html.erb
<%= form_for(@stock_item) do |f| %>
  <% if @stock_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock_item.errors.count, "error") %> prohibited this stock_item from being saved:</h2>

      <ul>
      <% @stock_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :products %><br />
    <%= f.text_field :products %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stock_items/edit.html.erb
<h1>Editing stock_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock_item %> |
<%= link_to 'Back', stock_items_path %>

app/views/stock_items/index.html.erb
<h1>Inventario</h1>

<table class="table">
  <tr>
    <th>Sucursal/Proveedor</th>
    <th>Producto</th>
    <th>Cantidad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stock_items.each do |stock_item| %>
  <tr>
    <td><%= stock_item.branches %></td>
    <td><%= stock_item.products %></td>
    <td><%= stock_item.quantity %></td>
    <td><%= link_to 'Show', stock_item %></td>
    <td><%= link_to 'Edit', edit_stock_item_path(stock_item) %></td>
    <td><%= link_to 'Destroy', stock_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stock item', new_stock_item_path %>

app/views/stock_items/new.html.erb
<h1>New stock_item</h1>

<%= render 'form' %>

<%= link_to 'Back', stock_items_path %>

app/views/stock_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Branches:</b>
  <%= @stock_item.branches %>
</p>

<p>
  <b>Products:</b>
  <%= @stock_item.products %>
</p>

<p>
  <b>Quantity:</b>
  <%= @stock_item.quantity %>
</p>


<%= link_to 'Edit', edit_stock_item_path(@stock_item) %> |
<%= link_to 'Back', stock_items_path %>