config/routes.rb
Tacosmode::Application.routes.draw do

  resources :stock_items

  match "users" => 'branches#index_users', :as=>'users'

  resources :products

  get "branches/:branch_id/transfers/new1" => 'transfers#new1', :as=>'new1_branch_transfer'  do
      resources :transfered_products
    end

  resources :branches do

    resources :transfers do
      resources :transfered_products
    end

    match "/transfers/:id/entry" => "transfers#entry", :as => 'entry' do
      resources :transfered_products
    end

  end

   root :to => 'branches#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tacosmode</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript">
    $(document).ready(function () {
        $('#transfer_date_output').datepicker();
        $('#transfer_date_output').datepicker('option', {dateFormat: 'yy-mm-dd'});
        $("#startDate").datepicker({dateFormat: 'yy-mm-dd'});
    });

  </script>


  <%= csrf_meta_tags %>
</head>
<body>
  <header>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">Tacos Mode</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active">
            <%= link_to 'Home', branches_path  %>
          </li>

          <li >
            <%= link_to 'Productos', products_path %>
          </li>

          <li>
            <%= link_to 'Inventario', stock_items_path %>
          </li>

          <li>
            <%= link_to 'Usuarios', users_path %>
          </li>

        </ul>
        <ul class="nav pull-right">
          <li>
            <a href="#">Sign in</a>
          </li>
        </ul>
      </div>

    </div>
  </div>
</div>



  </header>
  <div class="container">
  <%= yield %>
  </div>
</body>
</html>